In [36]:
import pandas as pd


arquivo_bovespa = './dados/COTAHIST_A2022.TXT'

tamanho_campos = [2,8,2,12,3,12,10,3,4,13,13,13,13,13,13,13,5,18,18,13,1,8,7,13,12,3]

dados_acoes = pd.read_fwf(arquivo_bovespa,widths=tamanho_campos)
dados_acoes.columns = [
    "tipo_registro",
    "data_pregao",
    "cod_bdi",
    "cod_negociacao",
    "tipo_mercado",
    "nome_empresa",
    "especificacao_papel",
    "prazo_dias_merc_termo",
    "moeda_referencia",
    "preco_abertura",
    "preco_maximo",
    "preco_minimo",
    "preco_medio",
    "preco_ultimo_negocio",
    "preco_melhor_oferta_compra",
    "preco_melhor_oferta_venda",
    "numero_negocios",
    "quantidade_papeis_negociados",
    "volume_total_negociado",
    "preco_exercicio",
    "indicador_correcao_precos",
    "data_vencimento",
    "fator_cotacao",
    "preco_exercicio_pontos",
    "codigo_isin",
    "num_distribuicao_papel",
]

In [37]:
# Remove registros que não sejam do tipo 1

dados_acoes = dados_acoes[dados_acoes["tipo_registro"]==1]
dados_acoes = dados_acoes[(dados_acoes["preco_melhor_oferta_compra"]!=0) & (dados_acoes["preco_melhor_oferta_venda"]!=0)]

'''
    Deleta coluna não necessárias
'''
dados_acoes.drop('num_distribuicao_papel',inplace=True,axis=1)
dados_acoes.drop('preco_exercicio_pontos',inplace=True,axis=1)
dados_acoes.drop('volume_total_negociado',inplace=True,axis=1)
dados_acoes.drop('fator_cotacao',inplace=True,axis=1)
dados_acoes.drop('data_vencimento',inplace=True,axis=1)
dados_acoes.drop('indicador_correcao_precos',inplace=True,axis=1)
dados_acoes.drop('preco_exercicio',inplace=True,axis=1)
dados_acoes.drop('tipo_registro',inplace=True,axis=1)
dados_acoes.drop('prazo_dias_merc_termo',inplace=True,axis=1)
dados_acoes.drop('moeda_referencia',inplace=True,axis=1)
dados_acoes.drop('codigo_isin',inplace=True,axis=1)
dados_acoes.drop('nome_empresa',inplace=True,axis=1)
dados_acoes.drop('especificacao_papel',inplace=True,axis=1)

listaNumber = [
    "preco_abertura",
    "preco_maximo",
    "preco_minimo",
    "preco_medio",
    "preco_ultimo_negocio",
    "preco_melhor_oferta_compra",
    "preco_melhor_oferta_venda",
]
listaInt = [
    "quantidade_papeis_negociados",
    "numero_negocios",
    "cod_bdi",
    "tipo_mercado",
]

for column in listaNumber:
    dados_acoes[column]=[i/100. for i in dados_acoes[column]]

for column in listaInt:
    dados_acoes[column]=[int(i) for i in dados_acoes[column]]

In [38]:
dados_acoes.columns = [
    "trading_date",
    "bdi_code",
    "stock_name",
    "market_type",
    "price_open",
    "price_max",
    "price_min",
    "price_avg",
    "price_last_deal",
    "price_best_buy_offer",
    "price_best_sell_offer",
    "quantity_papers_negotiated",
    "number_trades"
]

In [40]:
dados_acoes[dados_acoes['stock_name']=='ITSA4']

,trading_date,bdi_code,stock_name,market_type,price_open,price_max,price_min,price_avg,price_last_deal,price_best_buy_offer,price_best_sell_offer,quantity_papers_negotiated,number_trades
453,20220103,2,ITSA4,10,9.02,9.19,8.92,9.02,9.02,9.02,9.03,28501,28542600
2094,20220104,2,ITSA4,10,9.03,9.17,8.97,9.04,9.09,9.08,9.09,31880,38831200
3754,20220105,2,ITSA4,10,9.05,9.11,8.92,9.00,8.99,8.98,8.99,30251,34712800
5384,20220106,2,ITSA4,10,8.98,9.14,8.94,9.06,9.07,9.06,9.07,31789,25383800
6993,20220107,2,ITSA4,10,9.07,9.19,9.01,9.12,9.18,9.17,9.18,25949,21446300
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1041291,20220715,2,ITSA4,10,8.11,8.39,8.05,8.27,8.35,8.34,8.35,22393,28416500
1042981,20220718,2,ITSA4,10,8.29,8.54,8.28,8.44,8.43,8.42,8.43,28698,24600600
1044673,20220719,2,ITSA4,10,8.48,8.64,8.42,8.55,8.59,8.58,8.59,25642,19393500
1046359,20220720,2,ITSA4,10,8.58,8.59,8.44,8.48,8.46,8.46,8.47,16587,16462200
1048030,20220721,2,ITSA4,10,8.47,8.58,8.38,8.51,8.56,8.56,8.57,18650,14112500

In [33]:
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os

load_dotenv()

engine = create_engine("mysql+pymysql://{user}:{pw}@{host}/{db}"
    .format(user=os.environ['DB_USER'],
            host=os.environ['DB_HOST'],
            pw=os.environ['DB_PASSWORD'],
            db=os.environ['DB_DATABASE']))

In [35]:
dados_acoes.to_sql('acao_historico',con=engine,if_exists ='append',chunksize =10000,index=False)

525514

In [32]:
'''
    Alguns tipos de mercado:

    10 - mercado a vista
    70 - opções de compra
    80 - opções de venda


    filtro:
    dados_acoes[dados_acoes['tipo_mercado']==70]

'''

dados_acoes['cod_bdi'].unique()

array([ 2.,  5.,  7.,  8., 10., 12., 13., 14., 22., 96., 50., 58., 52.,
       62., 74., 75., 78., 82., 38., 32., 33., 42.])

In [52]:
dados_acoes[dados_acoes['cod_negociacao']=='NUBR33']

,data_pregao,cod_bdi,cod_negociacao,tipo_mercado,nome_empresa,especificacao_papel,preco_abertura,preco_maximo,preco_minimo,preco_medio,preco_ultimo_negocio,preco_melhor_oferta_compra,preco_melhor_oferta_venda,numero_negocios,quantidade_papeis_negociados,codigo_isin
574,20220103,2.0,NUBR33,10,NU-NUBANK,DR3,8.78,9.40,8.78,9.18,9.30,9.29,9.30,36259.0,2409380.0,BRNUBRBDR002
2225,20220104,2.0,NUBR33,10,NU-NUBANK,DR3,9.32,9.70,8.92,9.35,9.18,9.17,9.18,31316.0,2491130.0,BRNUBRBDR002
3881,20220105,2.0,NUBR33,10,NU-NUBANK,DR3,9.02,9.23,8.48,8.75,8.55,8.55,8.60,33245.0,2959260.0,BRNUBRBDR002
5506,20220106,2.0,NUBR33,10,NU-NUBANK,DR3,8.65,8.99,8.05,8.58,8.99,8.95,8.99,35817.0,2370140.0,BRNUBRBDR002
7112,20220107,2.0,NUBR33,10,NU-NUBANK,DR3,8.60,9.07,8.57,8.80,8.66,8.66,8.75,24806.0,1499690.0,BRNUBRBDR002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1041414,20220715,2.0,NUBR33,10,NU-NUBANK,DR3,3.50,3.56,3.37,3.45,3.39,3.39,3.40,11362.0,10456550.0,BRNUBRBDR002
1043110,20220718,2.0,NUBR33,10,NU-NUBANK,DR3,3.55,3.63,3.48,3.54,3.48,3.48,3.49,11252.0,7255490.0,BRNUBRBDR002
1044800,20220719,2.0,NUBR33,10,NU-NUBANK,DR3,3.55,3.66,3.50,3.57,3.65,3.64,3.65,9650.0,6933640.0,BRNUBRBDR002
1046483,20220720,2.0,NUBR33,10,NU-NUBANK,DR3,3.65,4.18,3.61,4.00,4.18,4.17,4.18,16987.0,11072790.0,BRNUBRBDR002
1048158,20220721,2.0,NUBR33,10,NU-NUBANK,DR3,4.14,4.24,3.97,4.09,4.12,4.11,4.12,12065.0,7355340.0,BRNUBRBDR002